### DISCUSSION TITLE
How to make the menu bar a bit less compact?

### DISCUSSION THREAD

**Discussion by ghost** [SpartanJ/ecode#540] [Q&A] [answered]
Only a bit, though. I want to have a bit more space between menu entries (in other words, making the menu entry a bit larger). I think there could be some CSS tricks. Increasing the UI font size or the scale factor definitely doesn't help.

I posted it in the `Issues` page because I think if you also agree with me about this, it's better to make it the default setting.

**Comment by SpartanJ** [comment]
You just need to set the height of the menubar in the `style.css` file:
In linux the path is: `~/.config/ecode/style.css`
macOS: `~/Library/Application Support/ecode/style.css`
Windows: `C:\Users\{username}\AppData\Roaming\ecode\style.css`
(i'll add this to the documentation, I think I forgot about it)

Example:
```css
menubar {
	height: 36dp;
}
```

**Comment by SpartanJ** [comment]
Oh I miss-read, between menu entries... let me check...

**Comment by SpartanJ** [comment]
Try something like:

```css
menubar > menubar::button {
	margin-left: 4dp;
	margin-right: 4dp;
	padding-left: 8dp;
	padding-right: 8dp;
}
```

It's hard to make a full documentation for each case, you'll need to read the eepp CSS documentation which is huge: https://eepp.ensoft.dev/page_cssspecification.html

**Comment by SpartanJ** [comment]
> I think if you also agree with me about this, it's better to make it the default setting.

I'll change the default padding to 8dp instead of the current 4dp, yeah, i makes sense.

**Comment by ghost** [comment]
> Try something like:
> 
> menubar > menubar::button {
> 	margin-left: 4dp;
> 	margin-right: 4dp;
> 	padding-left: 8dp;
> 	padding-right: 8dp;
> }
> 
> It's hard to make a full documentation for each case, you'll need to read the eepp CSS documentation which is huge: https://eepp.ensoft.dev/page_cssspecification.html

Hi. I'm talking about menu entries, not the menus. For example, `File` is a menu. `File -> New File` and `File -> New Terminal` are menu entries. This is not what I want.

**Comment by ghost** [comment]
Consider each menu and each menu entry as a rectangle. I want to know how to make this rectangle a bit larger.

**Comment by SpartanJ** [comment, marked as answer]
Sure, follow the same logic (but I won't add padding to these, I think they're OK now, adding space will make the menu less usable in small screens):

```css
Menu::Item,
Menu::CheckBox,
Menu::Separator,
Menu::SubMenu,
Menu::RadioButton
{
	padding-top: 4dp;
	padding-bottom: 4dp;
}
```

**Comment by ghost** [comment]
I want to make the menu bar a bit larger, too. The entries in the left panel should also be larger. And is it possible to add some insulation space between the menu bar and the rest? Currently the menu bar and the tab bar are touching each other.

**Comment by SpartanJ** [comment]
> I want to make the menu bar a bit larger, too.
>  Currently the menu bar and the tab bar are touching each other.

Larger how? I already mentioned how to change its height and separate the menu buttons. IDK what you mean. Maybe also add some margin? `margin-bottom: 4dp` to the `menubar`.

> The entries in the left panel should also be larger.

Define larger please. Bigger font and more separation between entries?
Panel font size is set in the settings: `Settings -> Window -> UI Panel Font Size`

**Comment by ghost** [comment]
I don't want the fonts to be larger. I'm talking about space (more separation). I also want to know if I could add some space between the menu bar and the tab bar. Currently they are touching each other.

**Comment by SpartanJ** [comment]
For tree views you need to set the row height.
For the menubar as I said before, add some margin.

```css
#project_view {
	row-height: 24dp;
}

menubar {
	margin-bottom: 8dp;
}
```

**Comment by ghost** [comment]
How to make the bottom bar (`Locate`, `Search`,...) larger, too? I don't even know what this bar is called.

**Reply by SpartanJ** [reply]
```css
#status_bar {
	height: 24dp;
}
```

**Reply by ghost** [reply]
How to increase the font size of the status bar (make the text `Locate`, `Search`,... larger)?

Can I do this only to the status bar? I don't want to change the global UI font size and UI panel font size (have never tried to see if these affect the font size of the status bar, though).

**Reply by SpartanJ** [reply]
Something like:
```css
#status_bar > * {
	font-size: 14dp!important;
}
```
