### ISSUE TITLE
Can I disable the graphical effect when doing Ctrl+S?

### ISSUE THREAD

**Issue by Curculigo** [SpartanJ/ecode#401]
I don't like it.

**Comment by SpartanJ** [comment]
You can disable the transformation / animation by overriding the CSS rule for the animation (i guess you're referring to that).

Add to your `style.css` (I think you were already using it):

```css
#code_container Tab {
	transition: background-color 0s!important;
}

#code_container Tab > Tab::close {
	transition: all 0s!important;
}
```
