### ISSUE TITLE
Improve active vs inactive file tab contrast

### ISSUE THREAD

**Issue by andy0x10** [SpartanJ/ecode#46]
![image](https://user-images.githubusercontent.com/124288474/218257605-daf38b95-fbb0-423f-8e76-24f478502122.png)

I find it difficult to easily tell which file tab is currently selected at a glance.

Perhaps some way to increase the contract between the selected vs the deselected tabs? Maybe darken the deselected tabs slightly or something?

Thanks,

**Comment by SpartanJ** [comment]
It's perfectly visible to me, I think this has to do with the color accuracy of the monitor. You can easily configure it as you with a custom stylesheet.
Create a CSS file with something like:
```css
Tab {
	background-color: #171819!important;
}

Tab:hover {
	background-color: #5f6b78!important;
}
Tab:selected {
	background-color: #3f4b58!important;
}
```

Let's name it "custom.css".

Now you juts have to run ecode with a parameter to load the CSS:
ecode.exe --css="C:\path\to\custom.css"

And that's it. I'll probably add and an option to auto-load a custom CSS in the configuration folder.

Customizing ecode's UI is very very easy. 

Result:
![Screenshot_20230211_131217](https://user-images.githubusercontent.com/650416/218268637-3b45c206-0864-4eac-8d3d-008851885fb6.png)

**Comment by andy0x10** [comment]
Nice!

**Comment by chadchoi** [comment]
> It's perfectly visible to me, I think this has to do with the color accuracy of the monitor. You can easily configure it as you wish a custom stylesheet. Create a CSS file with something like:
> 
> ```css
> Tab {
> 	background-color: #171819!important;
> }
> 
> Tab:hover {
> 	background-color: #5f6b78!important;
> }
> Tab:selected {
> 	background-color: #3f4b58!important;
> }
> ```
> 
> Let's name it "custom.css".
> 
> Now you juts have to run ecode with a parameter to load the CSS: ecode.exe --css="C:\path\to\custom.css"
> 
> And that's it. I'll probably add and an option to auto-load a custom CSS in the configuration folder.
> 
> Customizing ecode's UI is very very easy.
> 
> Result: ![Screenshot_20230211_131217](https://user-images.githubusercontent.com/650416/218268637-3b45c206-0864-4eac-8d3d-008851885fb6.png)

I have tried the CSS. How to make it the reverse, that the active tab is darkened instead of the inactive tabs?

**Comment by SpartanJ** [comment]
Invert the colors?
```css
Tab {
	background-color: #3f4b58!important;
	color: var(--font);
}

Tab:hover {
	background-color: #5f6b78!important;
}

Tab:selected {
	background-color: #171819!important;
}
```
